<a href="https://colab.research.google.com/github/kamo1010/injury-big-data/blob/main/Untitled3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install --upgrade category_encoders

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.2)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.23.5)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.2.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.10.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.0)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.3)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2023.3)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from patsy>=0.5.1->category_encoders) (1.16.0)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.3.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.2.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (23.1)

In [ ]:
pip install --upgrade catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.23.5)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.5.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.10.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.1.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.42.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (23.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.3)

In [41]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
from sklearn.metrics import classification_report
from sklearn.utils.class_weight import compute_class_weight
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split
from sklearn.feature_selection import SelectFromModel
from sklearn.preprocessing import StandardScaler, OneHotEncoder, PowerTransformer, PolynomialFeatures
from category_encoders import WOEEncoder, BinaryEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from lightgbm import LGBMClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier

In [147]:
df = pd.read_csv("sample_data/labels.csv", sep=",", encoding= 'utf-8')
df = df.loc[:, df.isna().sum()<712]
df.drop(columns=['연번', '호이스트'], inplace=True)

df.rename(columns = {'년도':'year', '월':'month', '일':'day', '평일/주말': 'day_of_week', '주야간':'day_or_night', '시간대':'period'}, inplace = True)
df.rename(columns = {'호기':'vehicle_number', '기상\r\n조건':'weather', '임무\r\n지시':'order', '상급부대': 'location', '환자신분':'patient_category', '환자\r\n증상':'injury'}, inplace = True)
df.rename(columns = {'환자유형 (외상 / 골절 / 심장 / 뇌 / 화상 / 기타)':'injury_type', '접수/이륙':'registration_takeoff', '출동시간':'departure_delay', '환자 인수지역 (PZ)': 'pz', 'PZ 도착/이륙':'pz_arrival_takeoff', '환자 후송지역 (LZ)':'lz'}, inplace = True)
df.rename(columns = {'LZ도착':'lz_arrival', '복귀이륙/복귀도착':'takeoff_arrival_at_basement', '출동~병원':'transfer_delay', '후송결과': 'y', '비고':'comment', '기상악화':'weather_deterioration'}, inplace = True)
df.columns

df.head(5)

,year,month,day,day_of_week,day_or_night,period,vehicle_number,weather,order,location,...,pz,pz_arrival_takeoff,lz,lz_arrival,takeoff_arrival_at_basement,transfer_delay,y,comment,NFL,weather_deterioration
0,2015,5,4,월,주간,12~18,NaN,GO,포천,5군단,...,일동병원,1500/\r\n1505,수도병원,1524,1526/\r\n1557,32분,생존,NaN,긴급후송,NaN
1,2015,5,13,수,주간,12~18,NaN,GO,춘천,7군단,...,홍천병원,1302/\r\n1315,수도병원,1351,1533/\r\n1600,61분,생존,NaN,,NaN
2,2015,5,14,목,주간,12~18,NaN,GO,포천,동원전력사,...,"운천,\r\n중군봉패드",1234/\r\n1236,수도병원,1259,1303/\r\n1327,43분,생존,NaN,긴급후송,NaN
3,2015,5,15,금,주간,12~18,NaN,GO,춘천,3군단,...,춘천병원,1712/\r\n1713,수도병원,1737,1759/\r\n1830,30분,생존,NaN,,NaN
4,2015,5,18,월,주간,12~18,NaN,GO,춘천,7군단,...,"인제, 2사단 17연대패드",1217/\r\n1219,수도병원,1253,1320/\r\n1355,51분,생존,NaN,,NaN

In [150]:
"""df.period = df.period.apply(lambda x:x.replace(" ~ ", "~"))
df.replace({"00~07": "00~06", "12~19": "12~18"}, inplace=True)
df['period'].value_counts()

df.weather = df.weather.apply(lambda x:x.replace(' ', ''))
df['weather'].value_counts()
df['weather'] = df['weather'].map({'NO-GO':0, 'GO':1, 1:1, 0:0})

df['day_or_night'] = df['day_or_night'].map({'주간':1, '야간':0, 1:1, 0:0})

def fit_order(x):
  x.replace(' ', '')
  x.replace('예비', '')
  if ('/' in x):
    return pd.Series(x.split('/'))
  return pd.Series([x, ])
df[['order', 'change']] = df.order.apply(lambda x:fit_order(x))
df[['order', 'change']].value_counts()
df.loc[df['order']=='용인예비']

def fit_patient_category(x):
  if x in ['-', '???']:
    x.replace(x, '?')
  if x in ['장교', '부사관', '준사관']:
    x.replace(x, '간부')
  if x in ['장교\r\n병' '간부, 병', '간부/병']:
    x.replace(x, '간부/병')
    return pd.Series(x.split('/'))
  return pd.Series([x])
df[['patient_category', 'company']] = df.patient_category.apply(lambda x:fit_patient_category(x))
tmp = df.loc[df['company']=='병']
tmp['patient_category'] = tmp['company']
pd.concat([df, tmp])
df.drop(columns=['company'], inplace=True)

def fit_injury_type(x):
  categories = ["외상", "골절", "심장", "뇌", "호상", "절단", "의식저하", "폐", "기타"]
  for val in categories:
    if val in x:
      x = val
  if x in [""]:
    x = "뇌"
  if x not in categories:
    x = x
  return pd.Series([x])

df[['injury_type']] = df.injury_type.apply(lambda x:fit_injury_type(x))
df['injury_type'].unique()
#df.loc[df['injury_type'].contains("정단")]

def fit_registration_takeoff(x):
  x = x.replace("\r\n", "")
  x = x.replace(" ", "")
  x = x.replace("(용인)", "")
  if len(x) == 4:
    x = x+"/"+x
  if len(x) == 8:
    x = x[:4]+"/"+x[4:]
  if len(x) == 13:
    x = x[:4]+"/"+x[9:]
  if x == "1757/1618":
    x = "1557/1618"
  if x == "2250/2058":
    x = "2250/2358"
  if x == "1159/0137":
    x = "2359/0137"
  return pd.Series([x])
df[['registration_takeoff']] = df.registration_takeoff.apply(lambda x:fit_registration_takeoff(x))
df['registration_takeoff'].unique()"""

def diff_delay(x):
  x = x.split("/")
  h = int(x[1][:2])-int(x[0][:2])
  if h < 0: h = 24+h
  r = h*60+(int(x[1][2:])-int(x[0][2:]))
  if r < 0: r = 1440+r
  return pd.Series([r])
"""
df[['departure_delay']] = df.registration_takeoff.apply(lambda x:diff_delay(x))
df['departure_delay'].unique()

def fit_pz(x):
  x = x.split("(")[0]
  x = x.replace("\r\n ", "\r\n")
  x = x.replace("\r\n", " ")
  x = x.replace(",", "")
  x = x.replace(" ", "")
  x = x.replace("패드", " PAD")
  x = x.replace(" PAD", "PAD")
  return pd.Series([x])
df[['pz']] = df.pz.apply(lambda x:fit_pz(x))
df['pz'].value_counts()

def fit_pz_arrival_takeoff(x):
  x = x.replace("\r\n", "")
  x = x.replace(" ", "")
  x = x.replace("(용인)", "")
  return pd.Series([x])
df[['pz_arrival_takeoff']] = df.pz_arrival_takeoff.apply(lambda x:fit_pz_arrival_takeoff(x))
df['pz_arrival_takeoff'].unique()
df[['patient_loading_delay']] = df.pz_arrival_takeoff.apply(lambda x:diff_delay(x))
df['patient_loading_delay'].unique()

def fit_lz(x):
  x = str(x).replace("\r\n", " ")
  return pd.Series([x])

df = df[df.lz.notnull()].query("lz != '-'")
df[['lz']] = df.lz.apply(lambda x:fit_lz(x))
df['lz'].value_counts()"""

def fit_lz_arrival(x):
  x = str(x).replace("\r\n", "")
  x = x.replace("/", "")
  x = x.replace("`", "")
  for i in range(4-len(x)):
    x = '0'+x
  return pd.Series([x])
df[['lz_arrival']] = df.query("lz_arrival != '×'").lz_arrival.apply(lambda x:fit_lz_arrival(x))
df['lz_arrival'].unique()

array(['1524', '1351', '1259', '1737', '1253', '1519', '0844', '0934',
       '1833', '2338', '1738', '0427', '2230', '0902', '1433', '0446',
       '1311', '2028', '0943', '1427', '1517', '1617', '1718', '0838',
       '0629', '0042', '0248', '1557', '1451', '1703', '1107', '1322',
       '1430', '0810', '1308', '1704', '1628', '1604', '2020', '1147',
       '1600', '0645', '1558', '1702', '1638', '2240', '0418', '2002',
       '2355', '0515', '1735', '1151', '0220', '0518', '0746', '1159',
       '1505', '1116', '0255', '1605', '1845', '1054', '1901', '0951',
       '1114', '1140', '1950', '1011', '2321', '1758', '1342', '1821',
       '0840', '0950', '1216', '0034', '1336', '2222', '1619', '1712',
       '2327', '0322', '1911', '1731', '1240', '1407', '1839', '1653',
       '1903', '1743', '1211', '2251', '1854', '2115', '1836', '1603',
       '0944', '1415', '1218', '1330', '1150', '2029', '1808', '1050',
       '1518', '1235', '1835', '1325', '1825', '1651', '1225', '2356',
       '1516', '2217', '2257', '1555', '1920', '0008', '1658', '1954',
       '1002', '0053', '1327', '1732', '1230', '2125', '1816', '1455',
       '1512', '2258', '2145', '1530', '1608', '1249', '1550', '1647',
       '1837', '1135', '2140', '1208', '1727', '2243', '1925', '1055',
       '0224', '0938', '1627', '1828', '2121', '1535', '1224', '2011',
       '1251', '2340', '1131', '0812', '1306', '2200', '1200', '1904',
       '1124', '1728', '2218', '1547', '2117', '1108', '1531', '1613',
       '0057', '1016', '0001', '1912', '0843', '1631', '1343', '1659',
       '0749', '1013', '1830', '1425', '1416', '1145', '1349', '1510',
       '1641', '1708', '1900', '1212', '1747', '1713', '2040', '1220',
       '1501', '1136', '1154', '1634', '1656', '1614', '0212', '1316',
       '1744', '1942', '0751', '2151', '2238', '1217', '000-', '0930',
       '1209', '1823', '0935', '0236', '1027', '1635', '2006', '2014',
       '1101', '0707', '2203', '1305', '2223', '1508', '1802', '1448',
       '1423', '1043', '2109', '1406', '2141', '2343', '1538', '1719',
       '0nan', '2137', '0820', '0612', '1300', '2018', '0337', '1717',
       '1834', '0941', '1811', '2131', '1846', '1739', '1313', '1947',
       '2108', '1929', '1829', '1746', '1832', '1326', '1915', '1228',
       '1234', '1533', '1417', '0904', '1439', '0900', '1414', '2154',
       '1324', '0101', '2318', '1040', '1458', '1246', '1556', '1730',
       '0316', '1642', '1059', '1650', '1630', '2035', '1122', '1625',
       '1153', '1748', '2306', '1919', '1045', '1602', '1015', '1426',
       '1130', '1721', '1633', '2236', '0000', '1110', '1447', '1341',
       '1541', '1036', '1328', '0923', '1723', '1851', '1358', '0836',
       '2244', '1626', '1039', '0831', '1757', '0009', '0002', '0339',
       '2204', '1710', '2214', '1445', '1118', '1438', '2045', '2034',
       '1705', '1842', '0044', '1814', '0045', '1736', '2022', '1623',
       '1742', '1120', '1607', '1046', '1333', '1244', '0939', '1859',
       '1354', '1908', '2010', '1233', '0206', '2135', '1250', '0048',
       '2105', '1522', '1344', '1202', '1449', '1257', '1933', '1841',
       '1238', '1644', '2341', '1048', '1652', '1714', '0825', '1749',
       '0922', '1520', '1332', '1004', '1210', '1359', '1404', '1152',
       '0731', '1543', '1141', '2201', '1611', '2101', '1031', '1119',
       '0210', '1247', '1201', '0004', '1601', '1849', '1337', '1121',
       '1132', '1444', '1815', '1318', '1411', '1133', '1546', '1529',
       '1606', '0003', '1754', '1654', '1214', '1431', '1812', '1226',
       '0817', '2003', '2156', '1657', '1852', '0834', '0907', '1709',
       '1237', '1850', '1005', '1034', '1826', '2111', '0619', '1622',
       '1405', '2350', '0145', '0726', '1428', '1126', '1539', '1229',
       '0837', '1025', '1910', '1021', '1113', '1148', '2150', '1817',
       '1352', '1231', '1001', '2235', '2326', '1213', '1914', '1302',
       '1858', '1459', '2254', '2053', '1855', '1205', '1945', '1610',
       '0646', '1707', '0745', '1053', '1204', '1503', '0120', '2044',
       '0730', '2000', '1526', '1701', '1008', '1042', '0910', '1317',
       '1203', '0135', '1256', '2312', '2314', '1525', '2144', '1319',
       '1621', '1506', '2133', '1309', '1421', '1553', '1955', '1643',
       '1243', '0735', '1129', '1252', '1109', '2241', '0020', '1437',
       '2335', '1722', '1227', '1400', '2138', '2:54', '2110', '1509',
       '0007', '2237', '0607', '1540', '0058', '2046', '1436', '1146',
       '0227', '1918', '1242', '1922', '1810', '1804', '1957', '0405',
       '0948', '1450', '1827', '1329'], dtype=object)

In [ ]:
scaler = StandardScaler()
onehot = OneHotEncoder(handle_unknown='ignore', sparse=False)
cv = StratifiedKFold(n_splits=5, random_state=1, shuffle=True)
df

,year,month,day,day_of_week,day_or_night,period,vehicle_number,weather,order,location,...,pz,pz_arrival/takeoff,lz,lz_arrival,takeoff_to_basement/arrival_at_basement,transfer_delay,y,comment,NFL,weather_deterioration
0,2015,5,4,월,1,12~18,NaN,1,포천,5군단,...,일동병원,1500/\r\n1505,수도병원,1524,1526/\r\n1557,32분,생존,NaN,긴급후송,NaN
1,2015,5,13,수,1,12~18,NaN,1,춘천,7군단,...,홍천병원,1302/\r\n1315,수도병원,1351,1533/\r\n1600,61분,생존,NaN,,NaN
2,2015,5,14,목,1,12~18,NaN,1,포천,동원전력사,...,"운천,\r\n중군봉패드",1234/\r\n1236,수도병원,1259,1303/\r\n1327,43분,생존,NaN,긴급후송,NaN
3,2015,5,15,금,1,12~18,NaN,1,춘천,3군단,...,춘천병원,1712/\r\n1713,수도병원,1737,1759/\r\n1830,30분,생존,NaN,,NaN
4,2015,5,18,월,1,12~18,NaN,1,춘천,7군단,...,"인제, 2사단 17연대패드",1217/\r\n1219,수도병원,1253,1320/\r\n1355,51분,생존,NaN,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
711,2023,5,23,화,1,12~18,1.0,1,용인,7군단,...,양촌리 헬기장,1441/1443,수도병원,/1458,1502/1515,26분,생존,NaN,NaN,NaN
712,2023,5,24,수,1,06~12,8.0,1,양구,3군단,...,대곡리헬기장,1143/1155,수도병원,/1233,1235/1309,48분,생존,NaN,NaN,NaN
713,2023,5,24,수,1,12~18,8.0,1,양구,2군단,...,춘천병원,1416/1425,수도병원,/1450,1451/1535,37분,생존,NaN,NaN,NaN
714,2023,5,31,수,1,12~18,5.0,1,포천,5군단,...,포천병원,1800/1805,수도병원,/1827,1830/1855,29분,생존,NaN,NaN,NaN
715,2023,6,2,금,1,12~18,6.0,1,양구,3군단,...,12사단 의무대 헬기장,1249/1252,수도병원,/1329,1333/1407,38분,생존,NaN,NaN,NaN

In [ ]:
model_logr = LogisticRegression(random_state=0)
# Split the data into features (X) and target (y)
X = df.drop('y', axis=1)
y = df['y']

scaler = StandardScaler()
onehot = OneHotEncoder(handle_unknown='ignore', sparse=False)
cv = StratifiedKFold(n_splits=5, random_state=1, shuffle=True)
feature = SelectFromModel(model_logr, threshold=0.001)
ct = ColumnTransformer([('onehot', onehot, cat_var), ('scaler', scaler, con_var)], remainder='passthrough', n_jobs=-1)

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
scores = cross_val_score(model_logr, X_train, y_train, scoring='accuracy', cv=cv, n_jobs=-1, verbose=0)

ValueError: ignored